//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Collections.Generic;

public struct FuzionTuple<T>
{
	string key;
	  T    value;
}

public class DialogTransition : FuzionEventArg
{

	int from_stateID;
	int to_stateID;

	List<FuzionTuple<T>> args;

	public DialogTransition(int from_stateID,int to_stateID, List<FuzionTuple<T>> _args)
	{
		args = _args;
	}
}


